# Generated by Django 3.0.7 on 2020-07-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogpost',
            new_name='blog_blogpost',
        ),
    ]
