# Generated by Django 3.0.7 on 2020-07-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200719_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_blogpost',
            new_name='Blogpost',
        ),
    ]
