# Generated by Django 3.0.7 on 2020-07-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200719_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
