# Generated by Django 3.0.7 on 2020-07-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('Category', models.CharField(default='', max_length=200)),
                ('sub_Category', models.CharField(default='', max_length=200)),
                ('Image', models.ImageField(default=0, upload_to='shop/images')),
                ('desc', models.CharField(max_length=40)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
