# Generated by Django 3.0.7 on 2020-07-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_name', models.CharField(max_length=10)),
                ('img', models.ImageField(default=0, upload_to='shop/images')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
