# Generated by Django 3.0.7 on 2020-07-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200713_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('region', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
