# Generated by Django 3.0.7 on 2020-07-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200721_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.CharField(default=0, max_length=111),
        ),
    ]
